# Generated by Django 3.1.4 on 2020-12-22 15:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scoreapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='games',
            name='date',
        ),
        migrations.AddField(
            model_name='games',
            name='gamedate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='gamedate'),
            preserve_default=False,
        ),
    ]
