# Generated by Django 3.1.4 on 2020-12-22 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoreapp', '0003_auto_20201222_1712'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gameses',
            new_name='Games',
        ),
    ]
