# Generated by Django 3.1.4 on 2020-12-22 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoreapp', '0004_auto_20201222_1714'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Games',
            new_name='Game',
        ),
    ]
