# Generated by Django 3.1.4 on 2020-12-31 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreapp', '0007_auto_20201227_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('user', models.CharField(max_length=200)),
                ('sent', models.BooleanField(default=False)),
            ],
        ),
    ]
