# Generated by Django 3.1.4 on 2020-12-31 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoreapp', '0008_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
