# Generated by Django 3.1.4 on 2021-01-02 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreapp', '0009_delete_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='mail',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
